name: cd test

on: [push]

defaults:
  run:
    working-directory: service

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
#      - name: Install SSH Key
#        uses: shimataro/ssh-key-action@v2
#        with:
#          key: ${{ secrets.DEPLOY }}
#          known_hosts: "ctrl-114514"
#      - name: Adding Known Hosts
#        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
#      - name: list dir
#        run: ls
#      - name: print full path
#        run: pwd
#      - name: Deploy with rsync
#        run:
#          rsync -avz . ${{ secrets.USER }}@${{ secrets.HOST }}:~/test
      - uses: actions/checkout@v2
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: .
          remote_path: ~/test
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
