name: cd test

on: [push]

defaults:
  run:
    working-directory: ./service

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY }}
          known_hosts: "ctrl-114514"
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run:
          rsync -avz ./ ${{ secrets.USER }}@${{ secrets.HOST }}:~/test
