name: Python Release

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r service.zip service/*
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN  }}
        automatic_release_tag: "latest"
        prerelease: false
        title: "Development Build"
        files: |
          web/*
          service/*
