name: Python Release

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: vimtor/action-zip@v1
      with:
        files: service/
        dest: service.zip
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.RELEASE_KEY }}
        prerelease: false
        files: |
          web/*
          service/*
